import { StyleSheet } from 'react-native'
import { theme } from '../../../core/theme'

export const styles = StyleSheet.create({
  container: { flex: 1, padding: 16, backgroundColor: theme.bg },
  inputSmall: { flex: 1, borderWidth: 1, borderColor: theme.border, borderRadius: 8, padding: 8, fontSize: 14, marginRight: 8, backgroundColor: theme.inputBg, color: theme.text },
  totalsCard: { backgroundColor: theme.surface, padding: 16, borderRadius: 12, marginBottom: 16, borderWidth: 1, borderColor: theme.border },
  totalText: { fontSize: 16, marginBottom: 4, color: theme.text },
  remainingText: { fontSize: 20, fontWeight: 'bold' },
  remainingPositive: { color: theme.success },
  remainingNegative: { color: theme.danger },
  addRow: { flexDirection: 'row', marginBottom: 8 },
  typeRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 16, gap: 8 },
  typeBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: theme.border },
  typeBtnActive: { backgroundColor: theme.primary, borderColor: theme.primary },
  typeBtnText: { color: theme.textSecondary },
  typeBtnTextActive: { color: '#fff' },
  addBtn: { backgroundColor: theme.primary, borderRadius: 8, paddingHorizontal: 16, paddingVertical: 8 },
  addBtnText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  historyBtn: { backgroundColor: theme.primary, borderRadius: 8, padding: 12, alignItems: 'center', marginBottom: 12 },
  historyBtnText: { color: '#fff', fontSize: 14, fontWeight: 'bold' },
  overlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: theme.bg, padding: 16, paddingTop: 60 },
  overlayHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  overlayTitle: { fontSize: 22, fontWeight: 'bold', color: theme.primaryLight },
  overlayClose: { fontSize: 22, color: theme.textSecondary, padding: 8 },
  historyCard: { backgroundColor: theme.surface, padding: 12, borderRadius: 8, marginBottom: 8, borderWidth: 1, borderColor: theme.border },
  historyMonth: { fontSize: 18, fontWeight: 'bold', color: theme.primaryLight, marginBottom: 4 },
  historyDetail: { fontSize: 14, color: theme.text, marginBottom: 2 },
  historyEmpty: { textAlign: 'center', marginTop: 40, fontSize: 16, color: theme.textMuted },
  sectionTitle: { fontSize: 14, fontWeight: '600', color: theme.textSecondary, marginBottom: 8, marginTop: 8 },
  expenseRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 8, paddingHorizontal: 12, backgroundColor: theme.surface, borderRadius: 8, marginBottom: 4, borderWidth: 1, borderColor: theme.border },
  expenseLabel: { color: theme.text, flex: 1 },
  expenseAmount: { color: theme.text },
  editRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 4 },
  editInput: { flex: 1, borderWidth: 1, borderColor: theme.primary, borderRadius: 6, padding: 6, fontSize: 14, backgroundColor: theme.inputBg, color: theme.text },
  saveBtn: { backgroundColor: theme.primary, borderRadius: 6, paddingHorizontal: 12, paddingVertical: 6 },
  saveBtnText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
})
