const fs = require('node:fs')
const path = require('node:path')

const ROOT = path.resolve(__dirname, '..')
const MODULES_DIR = path.join(ROOT, 'src', 'modules')
const CORE_DIR = path.join(ROOT, 'src', 'core')
const AUTO_IMPORTS_FILE = path.join(CORE_DIR, 'module-registry', 'auto-imports.ts')

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1)
}

function validateName(name) {
  return /^[a-z][a-z0-9_-]*$/.test(name)
}

function createDirectory(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
    console.log(`  Created: ${path.relative(ROOT, dir)}`)
  }
}

function writeFile(filePath, content) {
  fs.writeFileSync(filePath, content, 'utf-8')
  console.log(`  Created: ${path.relative(ROOT, filePath)}`)
}

function generateModuleFiles(name) {
  const moduleDir = path.join(MODULES_DIR, name)
  const dirs = ['domain', 'ui', 'tests']
  for (const dir of dirs) {
    createDirectory(path.join(moduleDir, dir))
  }

  // index.ts
  writeFile(
    path.join(moduleDir, 'index.ts'),
    `import type { AppModule } from '../../core/types';\nimport { ${capitalize(name)}Screen } from './ui/${capitalize(name)}Screen';\nimport { dbManager } from '../../core/db/db-manager';\n\nexport const ${capitalize(name)}Module: AppModule = {\n  id: '${name}',\n  name: '${capitalize(name)}',\n  icon: '📦',\n  screen: ${capitalize(name)}Screen,\n  init: async () => {\n    dbManager.registerModule('${name}');\n  },\n};\n`
  )

  // UI Screen
  writeFile(
    path.join(moduleDir, 'ui', `${capitalize(name)}Screen.tsx`),
    `import React, { useState } from 'react';\nimport { View, Text, TextInput, FlatList, TouchableOpacity, StyleSheet } from 'react-native';\nimport { dbManager } from '../../core/db/db-manager';\n\nconst db = dbManager.getDB('${name}');\n\ninterface Item {\n  id: string;\n  value: string;\n}\n\nexport function ${capitalize(name)}Screen() {\n  const [items, setItems] = useState<Item[]>(() => {\n    const saved = db.get('items');\n    return saved || [];\n  });\n  const [input, setInput] = useState('');\n\n  const addItem = () => {\n    if (!input.trim()) return;\n    const newItem: Item = { id: String(Date.now()), value: input };\n    const updated = [...items, newItem];\n    setItems(updated);\n    db.set('items', updated);\n    setInput('');\n  };\n\n  return (\n    <View style={styles.container}>\n      <Text style={styles.title}>${capitalize(name)}</Text>\n      <View style={styles.row}>\n        <TextInput style={styles.input} value={input} onChangeText={setInput} placeholder="Add item" />\n        <TouchableOpacity style={styles.addBtn} onPress={addItem}>\n          <Text style={styles.addBtnText}>+</Text>\n        </TouchableOpacity>\n      </View>\n      <FlatList\n        data={items}\n        keyExtractor={(item) => item.id}\n        renderItem={({ item }) => (\n          <View style={styles.card}>\n            <Text>{item.value}</Text>\n          </View>\n        )}\n      />\n    </View>\n  );\n}\n\nconst styles = StyleSheet.create({\n  container: { flex: 1, padding: 16, backgroundColor: '#f5f5f5' },\n  title: { fontSize: 24, fontWeight: 'bold', marginBottom: 16 },\n  row: { flexDirection: 'row', marginBottom: 16 },\n  input: { flex: 1, borderWidth: 1, borderColor: '#ccc', borderRadius: 8, padding: 10, fontSize: 16, marginRight: 8 },\n  addBtn: { backgroundColor: '#1976d2', borderRadius: 8, paddingHorizontal: 16, justifyContent: 'center' },\n  addBtnText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },\n  card: { backgroundColor: '#fff', padding: 12, borderRadius: 8, marginBottom: 8, elevation: 1 },\n});\n`
  )

  // Test file
  writeFile(
    path.join(moduleDir, 'tests', `${name}.test.ts`),
    `import { describe, it, expect } from 'vitest';\n\ndescribe('${capitalize(name)} Module', () => {\n  it('should be defined', () => {\n    expect(true).toBe(true);\n  });\n});\n`
  )
}

function updateAutoImports(name) {
  let content = fs.readFileSync(AUTO_IMPORTS_FILE, 'utf-8')

  const importLine = `import { ${capitalize(name)}Module } from '../../modules/${name}';`
  if (!content.includes(importLine)) {
    content = content.replace(
      /(\/\/ Auto-generated by CLI\. Do not edit manually\.\n)/,
      `$1${importLine}\n`
    )
  }

  const registerLine = `  registerModule(${capitalize(name)}Module);`
  if (!content.includes(registerLine)) {
    content = content.replace(
      /(export function registerAllModules\(\): void \{\n)/,
      `$1${registerLine}\n`
    )
  }

  fs.writeFileSync(AUTO_IMPORTS_FILE, content, 'utf-8')
  console.log(`  Updated: ${path.relative(ROOT, AUTO_IMPORTS_FILE)}`)
}

// --- Main ---
const args = process.argv.slice(2)
const moduleName = args[0]

if (!moduleName) {
  console.error('Usage: npm run create:module <module-name>')
  process.exit(1)
}

if (!validateName(moduleName)) {
  console.error('Error: Module name must be lowercase alphanumeric (hyphens/underscores allowed).')
  process.exit(1)
}

const moduleDir = path.join(MODULES_DIR, moduleName)
if (fs.existsSync(moduleDir)) {
  console.error(`Error: Module "${moduleName}" already exists at src/modules/${moduleName}`)
  process.exit(1)
}

console.log(`\nCreating module: ${moduleName}\n`)

generateModuleFiles(moduleName)
updateAutoImports(moduleName)

console.log(`\nModule "${moduleName}" created successfully!\n`)
console.log('Next steps:')
console.log(`  1. Implement your module in src/modules/${moduleName}/`)
console.log(`  2. Update the icon in src/modules/${moduleName}/index.ts`)
console.log('  3. Run "npm test" to verify')
